<?php
/*
 本代码由 PHP代码加密工具 Xend(Build 5.00.08) 创建
 创建时间 2019-04-23 14:56:54
 技术支持 QQ:30370740 Mail:support@phpXend.com
 严禁反编译、逆向等任何形式的侵权行为，违者将追究法律责任
*/

namespace App\Http\Controllers\Api;use App\Models\Search;use Illuminate\Http\Request;use App\Http\Controllers\Controller;use Auth;class SearchController extends Controller{public function store(Request $request){$user=Auth::user();$code=$request->code;$prices=get_price_moneys($code);$status='';$search=Search::where('user_id',$user->id)->where('code',$code)->first();if($search)goto H2tBodyx2;goto H2tNextx2;H2tBodyx2:return ['status'=>false,'msg'=>'该搜索历史已经存在'];goto H2tx1;H2tNextx2:H2tx1:if($prices)goto H2tBodyx4;goto H2tNextx4;H2tBodyx4:$status=Search::create(['user_id'=>$user->id,'code'=>$code]);goto H2tx3;H2tNextx4:return ['status'=>false,'该股票不存在'];H2tx3:if($status)goto H2tBodyx6;goto H2tNextx6;H2tBodyx6:return ['status'=>true,'msg'=>'写入成功'];goto H2tx5;H2tNextx6:return ['status'=>false,'msg'=>'搜索结果不存在'];H2tx5:}public function index(Request $request){$page=$request->page;$H2t0=$page-1;$page=$H2t0;$limit=5;$H2t0=$page*$limit;$offset=$H2t0;$user_id=Auth::user()->id;$selfstock=Search::where('user_id',$user_id)->offset($offset)->limit($limit)->orderBy('id','desc')->select('code')->get();$plucked=$selfstock->pluck('code');$plucked->all();$plucked=$plucked->implode(',');$list=get_price_moneys($plucked);if($list)goto H2tBodyx8;goto H2tNextx8;H2tBodyx8:return ['status'=>true,'data'=>$list];goto H2tx7;H2tNextx8:return ['status'=>false,'msg'=>'没有搜索历史'];H2tx7:}public function delete(Request $request){$user=Auth::user();$type=0;$code=0;$map['user_id']=$user->id;if($request->code)goto H2tBodyxa;goto H2tNextxa;H2tBodyxa:$code=$request->code;$map['code']=$code;goto H2tx9;H2tNextxa:H2tx9:if($request->type)goto H2tBodyxc;goto H2tNextxc;H2tBodyxc:$type=$request->type;goto H2txb;H2tNextxc:H2txb:$H2t0=!$code;$H2t2=(bool)$H2t0;if($H2t2)goto H2tBodyxf;goto H2tNextxf;H2tBodyxf:$H2t1=$type==0;$H2t2=(bool)$H2t1;goto H2txe;H2tNextxf:H2txe:if($H2t2)goto H2tBodyxg;goto H2tNextxg;H2tBodyxg:return ['status'=>false,'msg'=>'股票代码不存在'];goto H2txd;H2tNextxg:H2txd:$status=Search::where($map)->delete();if($status)goto H2tBodyxi;goto H2tNextxi;H2tBodyxi:return ['status'=>true,'msg'=>'删除成功'];goto H2txh;H2tNextxi:return ['status'=>false,'msg'=>'删除失败'];H2txh:}}
?>