<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Storage extends Model
{
    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($model) {
            $storage = Storage::where('xingyongjin',$model->xingyongjin)->where('multiple',$model->multiple)->where('cangfei',$model->cangfei)->first();
            if ($storage){
                admin_error('提示', '不能重复添加');
                return false;
            }
            //dd($storage);
        });
    }
}
